batch_queue: <queue_name>
scripts_dir: SpOOx/src

hyperion_dir: mcd
marker_file: markers_panel.tsv
signal_extraction_options: --verbose --distribution_crop_percentile 1.0 --doArcsinh
phenograph_options: --save_sceobj --datatransf scaledtrim --k 30 --q 0.001 --run_dimRed TRUE

zegami:
  stack_dir: zegamistacks
  dir: zegami
  project: <project_name>
  collection: <collection_name>